config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "boards#new"
  
  resources :boards

  namespace :form_validations do
    resources :boards, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class EmailValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
        unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
        record.errors.add attribute, (options[:message] || "is not an email")
        end
    end
end

class Board < ApplicationRecord
    has_many :board_mines, dependent: :destroy

    validates :name, presence: true
    validates :user_email, presence: true, email: true
    validates :mine_num, numericality: { only_integer: true }
    validates :height, comparison: { greater_than: 1 }, numericality: { only_integer: true }
    validates :width, comparison: { greater_than: 1 }, numericality: { only_integer: true }
    validate :mine_number
      
    def mine_number
        errors.add(:mine_num, "can't greather than multiplication of height and width") if !mine_num || mine_num > height * width
    end
end

app/models/board_mine.rb
class BoardMine < ApplicationRecord
    belongs_to :Board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @all = false
    @boards
    if (params[:all]) 
      @all = true
      @boards = Board.order("created_at DESC").limit(10)
    else
      @page = params[:page]
      @boards = Board.order("created_at DESC").paginate(page: @page, per_page: 10)
    end
  end

  def show
    @board = Board.find(params[:id])
    @mins = {}
    @board.board_mines.each do |mine|
      @mins["#{mine.row}-#{mine.col}"] = true;
    end
  end
  
  def new
    @board = Board.new
  end
  
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if !@board.save
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      else
        spaces = @board.width * @board.height
        mins = Array.new(spaces, 0)
        for i in 0..(@board.mine_num - 1)
          j = rand(spaces)
          while mins[j] == 1
            j += 1
          end
          mins[j] = 1
          spaces -= 1
        end
        boardMines = []
        for i in 0..(mins.length)
          if (mins[i] == 1)
            boardMines.push({board_id: @board.id, row: i / @board.width, col: i % @board.width})
          end
        end
        BoardMine.insert_all(boardMines)
        format.html { redirect_to @board, notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:name, :user_email, :height, :width, :mine_num)
  end
end

app/controllers/form_validations/boards_controller.rb
class FormValidations::BoardsController < BoardsController
  def create
    @board.assign_attributes(board_params)
    @board.validate
    respond_to do |format|
      format.text { render partial: 'boards/form', locals: { board: @board }, formats: [:html] } 
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, data: { form_validation_target: "form" }) do |form| %>
  <div class="row mb-2">
    <div class="col-2">
      <%= form.label(:name, class: "form-label")%>
    </div>
    <div class="col-4">
      <%= form.text_field :name, class: "form-control", data: { action: "form-validation#handleChange" } %>
      <% @board.errors.full_messages_for(:name).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-2">
      <%= form.label(:user_email, class: "form-label")%>
    </div>
    <div class="col-4">
      <%= form.text_field :user_email, class: "form-control", data: { action: "form-validation#handleChange" } %>
      <% @board.errors.full_messages_for(:user_email).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-2">
      <%= form.label(:width, class: "form-label")%>
    </div>
    <div class="col-4">
      <%= form.number_field :width, class: "form-control", data: { action: "form-validation#handleChange" } %>
      <% @board.errors.full_messages_for(:width).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-2">
      <%= form.label(:height, class: "form-label")%>
    </div>
    <div class="col-4">
      <%= form.number_field :height, class: "form-control", data: { action: "form-validation#handleChange" } %>
      <% @board.errors.full_messages_for(:height).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-2">
      <%= form.label(:mine_num, class: "form-label")%>
    </div>
    <div class="col-4">
      <%= form.number_field :mine_num, class: "form-control", data: { action: "form-validation#handleChange" } %>
      <% @board.errors.full_messages_for(:mine_num).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit 'Generate Board', :class=>"btn btn-success" %>
  </div>
<% end %>

app/views/boards/index.html.erb
<div class="container">
  <h1>Boards</h1>
  <table class="table striped-table text-center">
    <thead class="bg-primary text-white">
      <tr>
        <th>No</th>
        <th>Name</th>
        <th>Mine Number</th>
        <th>Created By</th>
        <th>Created At</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @boards.each_with_index do |board, index| %>
        <tr>
        <td><%= index +1 %></td>
        <td><a href="/boards/<%= board.id %>"><%= board.name %></a></td>
        <td><%= board.mine_num %></td>
        <td><%= board.user_email %></td>
        <td><%= board.created_at.strftime("%m/%d/%Y") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if (!@all) %>
    <div class="float-end">
      <%= will_paginate @boards, :container => false %>
    </div>
    <div class="pag">
      <div class="page_info">
        <%= page_entries_info @boards, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </div>
    </div>
  <% else %>
    <a class="btn btn-primary" href="/boards">view all generated boards</a>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="container">
  <h2 class="mb-5">New Board</h2>
  <div data-controller="form-validation" data-form-validation-target="output" data-form-validation-url-value="<%= form_validations_boards_path %>">
    <%= render 'form', board: @board %>
  </div>
  <div class="col-6">
    <%= link_to 'Back', boards_path, :class=>'btn btn-primary float-end' %>
  </div>

</div>

app/views/boards/show.html.erb
<div class="container">
  <h3><%= @board.name %> Board Created By <%= @board.user_email %></h3>
  <div class="center-block">
  <% for i in 0..(@board.height - 1) %>
    <div>
      <% for j in 0..(@board.width - 1) %>
        <%if (@mins["#{i}-#{j}"]) %>
          <div class="clone miner"></div>
        <% else %>
          <div class="clone empty"></div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <form class="container-fluid justify-content-start">
        <a href="/boards?all=true" class="btn btn btn-light me-2" type="button">Home</a>
        <a href="/boards" class="btn btn btn-light me-2" type="button">List</a>
        <a href="/boards/new" class="btn btn btn-light" type="button">Create</a>
      </form>
    </nav>
    <%= yield %>
  </body>
</html>